In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
(pd.__version__)

'2.2.3'

In [8]:

import pandas as Bhoomika
Vijayalaxmi=Bhoomika.Series([1,2,3,4,5])
Vijayalaxmi

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
import pandas as pd
marks=pd.Series([85,90,75,95])
marks

0    85
1    90
2    75
3    95
dtype: int64

In [23]:
import pandas as pd
student = {'Rahul':85,
           'Anita':92,
           'John':78}
s=pd.Series(student)
print(s)

Rahul    85
Anita    92
John     78
dtype: int64

In [24]:
import pandas as pd
Num=(5,10,15,20)
data=pd.Series(Num)
print(data)

0     5
1    10
2    15
3    20
dtype: int64

In [22]:
import pandas as pd
Num=[10,15,25,40,100,500]
data=pd.Series(Num)
print(data)

0     10
1     15
2     25
3     40
4    100
5    500
dtype: int64

In [29]:
import numpy as np
arr=np.array([10,20,30,40])
s=pd.Series(arr)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [31]:
import pandas as pd
demo=[1,3,6,8,4,7,3,8,5,8,0]
print(demo)
new=pd.Series(demo)
new

[1, 3, 6, 8, 4, 7, 3, 8, 5, 8, 0]

0     1
1     3
2     6
3     8
4     4
5     7
6     3
7     8
8     5
9     8
10    0
dtype: int64

In [43]:
#dict to pandas Series
import pandas as pd
student={'Name':"bhoomika",
         'Reg_No':206,
         'Place':"gadag",
         'College':"Jt College",
         'Year':2026,
         'Result':"Pass"}
student
demo=pd.Series(student)
demo
print(demo[1])
print(demo['Result'])
print(demo[-2])

206
Pass
2026

/tmp/ipykernel_5203/1776569894.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[1])
/tmp/ipykernel_5203/1776569894.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[-2])

In [45]:
import pandas as pd
arr=[86,45,89,34,67,88,94,12]
data=pd.Series(arr)
data
print(data[data>82])

0    86
2    89
5    88
6    94
dtype: int64

In [55]:
import numpy as np
import pandas as pd
arr=np.array([80,90,95])
arr+=5
arr
new=pd.Series(arr)
new
print(new*2)
print(new[new>80])
print(new.dtype)
print(new.shape)
print(new.size)
print(new.index)
print(new.values)

0    170
1    190
2    200
dtype: int64
0     85
1     95
2    100
dtype: int64
int64
(3,)
3
RangeIndex(start=0, stop=3, step=1)
[ 85  95 100]

In [56]:
pip install excel

Collecting excel
  Downloading excel-1.0.1-py2.py3-none-any.whl.metadata (728 bytes)
Downloading excel-1.0.1-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: excel
Successfully installed excel-1.0.1

In [61]:
#DataFrame Programs
#1) Dict to DataFrame
import pandas as pd
demo={'Reg No':[11,12,13,14,15,16],
      'Name':['Sharath','Keerthi','pruthvi','bhoomika','akhil','Shivu'],
      'Age':[34,29,26,30,27,19],
      'Place':['Gadag','Malavalli','Hassan','KR Road','Pavagad','Badami']}
demo
data=pd.DataFrame(demo)
data

   Reg No      Name  Age      Place
0      11   Sharath   34      Gadag
1      12   Keerthi   29  Malavalli
2      13   pruthvi   26     Hassan
3      14  bhoomika   30    KR Road
4      15     akhil   27    Pavagad
5      16     Shivu   19     Badami

In [62]:
# 2) csv file to DataFrame
import pandas as pd
data=pd.read_csv("/content/Employee.csv")
data

   Emp id         Name  Salary   Comapany
0     206     Bhoomika   80000  microsoft
1     207  Vijayalaxmi  100000    infosys
2     213    Aishwarya   20000        TCS
3     153     Harshita   50000      Wipro
4     214        veena   40000  Accenture